"""Services subpackage — shared business logic and repository layers."""

from common.services.hub_repository import (
    HubRepositoryError,
    HubNotFoundError,
    HubArchivedError,
    HubNotEmptyError,
    LastOwnerError,
    DuplicateSlugError,
    InvalidLinkDirectionError,
    get_hub,
    get_hub_by_slug,
    list_hubs_for_user,
    create_hub,
    update_hub,
    archive_hub,
    delete_hub_if_empty,
    get_membership,
    list_members,
    count_owners,
    upsert_member,
    remove_member,
    list_links,
    get_link,
    create_link,
    list_bindings,
    get_scoped,
    list_scoped,
)

__all__ = [
    "HubRepositoryError",
    "HubNotFoundError",
    "HubArchivedError",
    "HubNotEmptyError",
    "LastOwnerError",
    "DuplicateSlugError",
    "InvalidLinkDirectionError",
    "get_hub",
    "get_hub_by_slug",
    "list_hubs_for_user",
    "create_hub",
    "update_hub",
    "archive_hub",
    "delete_hub_if_empty",
    "get_membership",
    "list_members",
    "count_owners",
    "upsert_member",
    "remove_member",
    "list_links",
    "get_link",
    "create_link",
    "list_bindings",
    "get_scoped",
    "list_scoped",
]
