"""add_guardroute_tables

Revision ID: 3c291ab4e81e
Revises: d2e57c967822
Create Date: 2026-07-10 17:54:29.459904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c291ab4e81e'
down_revision: Union[str, Sequence[str], None] = 'd2e57c967822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardroute_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('complexity', sa.String(length=50), nullable=True),
    sa.Column('subagents_ran', sa.JSON(), nullable=True),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardroute_sessions_id'), 'guardroute_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_guardroute_sessions_session_id'), 'guardroute_sessions', ['session_id'], unique=False)
    op.create_table('guardroute_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardroute_usage_id'), 'guardroute_usage', ['id'], unique=False)
    op.create_index(op.f('ix_guardroute_usage_session_id'), 'guardroute_usage', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guardroute_usage_session_id'), table_name='guardroute_usage')
    op.drop_index(op.f('ix_guardroute_usage_id'), table_name='guardroute_usage')
    op.drop_table('guardroute_usage')
    op.drop_index(op.f('ix_guardroute_sessions_session_id'), table_name='guardroute_sessions')
    op.drop_index(op.f('ix_guardroute_sessions_id'), table_name='guardroute_sessions')
    op.drop_table('guardroute_sessions')
    # ### end Alembic commands ###
