"""add_workflows_table

Revision ID: 7e992fb9475e
Revises: 85e2f0c51f71
Create Date: 2026-07-21 13:10:05.670772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e992fb9475e'
down_revision: Union[str, Sequence[str], None] = '85e2f0c51f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('graph_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_is_active'), 'workflows', ['is_active'], unique=False)
    op.add_column('syntraflow_chunks', sa.Column('image_path', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_syntraflow_chunks_document_id'), 'syntraflow_chunks', ['document_id'], unique=False)
    op.drop_constraint(op.f('syntraflow_chunks_document_id_fkey'), 'syntraflow_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'syntraflow_chunks', 'syntraflow_documents', ['document_id'], ['id'])
    op.alter_column('syntraflow_documents', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('syntraflow_jobs', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::character varying"))
    op.alter_column('syntraflow_jobs', 'error_msg',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('syntraflow_jobs_document_id_fkey'), 'syntraflow_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'syntraflow_jobs', 'syntraflow_documents', ['document_id'], ['id'])
    op.alter_column('syntraflow_video_segments', 'emotion_tags',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('syntraflow_video_segments_document_id_fkey'), 'syntraflow_video_segments', type_='foreignkey')
    op.create_foreign_key(None, 'syntraflow_video_segments', 'syntraflow_documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'syntraflow_video_segments', type_='foreignkey')
    op.create_foreign_key(op.f('syntraflow_video_segments_document_id_fkey'), 'syntraflow_video_segments', 'syntraflow_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.alter_column('syntraflow_video_segments', 'emotion_tags',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_constraint(None, 'syntraflow_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('syntraflow_jobs_document_id_fkey'), 'syntraflow_jobs', 'syntraflow_documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.alter_column('syntraflow_jobs', 'error_msg',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('syntraflow_jobs', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::character varying"))
    op.alter_column('syntraflow_documents', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'syntraflow_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('syntraflow_chunks_document_id_fkey'), 'syntraflow_chunks', 'syntraflow_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_syntraflow_chunks_document_id'), table_name='syntraflow_chunks')
    op.drop_column('syntraflow_chunks', 'image_path')
    op.drop_index(op.f('ix_workflows_is_active'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
