"""add_workflows_table

Revision ID: 7e992fb9475e
Revises: 85e2f0c51f71
Create Date: 2026-07-21 13:10:05.670772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e992fb9475e'
down_revision: Union[str, Sequence[str], None] = '85e2f0c51f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('graph_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_is_active'), 'workflows', ['is_active'], unique=False)
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    op.add_column('syntraflow_chunks', sa.Column('image_path', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_syntraflow_chunks_document_id'), 'syntraflow_chunks', ['document_id'], unique=False)
    if not is_sqlite:
        op.drop_constraint(op.f('syntraflow_chunks_document_id_fkey'), 'syntraflow_chunks', type_='foreignkey')
        op.create_foreign_key(None, 'syntraflow_chunks', 'syntraflow_documents', ['document_id'], ['id'])
    with op.batch_alter_table('syntraflow_documents') as batch_op:
        batch_op.alter_column('content', existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table('syntraflow_jobs') as batch_op:
        batch_op.alter_column('status', existing_type=sa.VARCHAR(length=32), type_=sa.String(length=20), existing_nullable=False)
        batch_op.alter_column('error_msg', existing_type=sa.VARCHAR(length=512), type_=sa.Text(), existing_nullable=True)
        if not is_sqlite:
            batch_op.drop_constraint(op.f('syntraflow_jobs_document_id_fkey'), type_='foreignkey')
            batch_op.create_foreign_key(None, 'syntraflow_documents', ['document_id'], ['id'])

    with op.batch_alter_table('syntraflow_video_segments') as batch_op:
        batch_op.alter_column('emotion_tags', existing_type=sa.VARCHAR(length=128), type_=sa.String(length=255), existing_nullable=True)
        if not is_sqlite:
            batch_op.drop_constraint(op.f('syntraflow_video_segments_document_id_fkey'), type_='foreignkey')
            batch_op.create_foreign_key(None, 'syntraflow_documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    with op.batch_alter_table('syntraflow_video_segments') as batch_op:
        if not is_sqlite:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.create_foreign_key(op.f('syntraflow_video_segments_document_id_fkey'), 'syntraflow_documents', ['document_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('emotion_tags', existing_type=sa.String(length=255), type_=sa.VARCHAR(length=128), existing_nullable=True)

    with op.batch_alter_table('syntraflow_jobs') as batch_op:
        if not is_sqlite:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.create_foreign_key(op.f('syntraflow_jobs_document_id_fkey'), 'syntraflow_documents', ['document_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('error_msg', existing_type=sa.Text(), type_=sa.VARCHAR(length=512), existing_nullable=True)
        batch_op.alter_column('status', existing_type=sa.String(length=20), type_=sa.VARCHAR(length=32), existing_nullable=False)

    with op.batch_alter_table('syntraflow_documents') as batch_op:
        batch_op.alter_column('content', existing_type=sa.TEXT(), nullable=True)

    with op.batch_alter_table('syntraflow_chunks') as batch_op:
        if not is_sqlite:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.create_foreign_key(op.f('syntraflow_chunks_document_id_fkey'), 'syntraflow_documents', ['document_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(op.f('ix_syntraflow_chunks_document_id'))
        batch_op.drop_column('image_path')

    op.drop_index(op.f('ix_workflows_is_active'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
