"""add_provider_credential

Revision ID: 9505282eda4d
Revises: j1e2f3a4b5c6
Create Date: 2026-08-05 13:17:24.097396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9505282eda4d'
down_revision: Union[str, Sequence[str], None] = 'j1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_credentials_provider'), ['provider'], unique=True)

    with op.batch_alter_table('agent_definitions', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.create_index(batch_op.f('ix_agent_definitions_endpoint_slug'), ['endpoint_slug'], unique=False)

    with op.batch_alter_table('eval_flow_traces', schema=None) as batch_op:
        batch_op.alter_column('workflow_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=True)
        if op.get_bind().dialect.name != "sqlite":
            try:
                batch_op.drop_constraint(batch_op.f('eval_flow_traces_run_id_fkey'), type_='foreignkey')
            except Exception:
                pass
            batch_op.create_foreign_key(None, 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
            batch_op.create_foreign_key(None, 'workflow_runs', ['run_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('eval_run_history', schema=None) as batch_op:
        batch_op.alter_column('target_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'agent'::character varying"))
        batch_op.alter_column('target_hub_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('target_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('eval_test_suites', schema=None) as batch_op:
        batch_op.alter_column('target_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'agent'::character varying"))
        batch_op.alter_column('target_hub_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('target_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('syntraflow_collections', schema=None) as batch_op:
        batch_op.alter_column('physical_name',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=320),
               existing_nullable=False)
        batch_op.alter_column('vector_dimension',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('1024'))
        if op.get_bind().dialect.name != "sqlite":
            inspector = sa.inspect(op.get_bind())
            existing_uqs = {c["name"] for c in inspector.get_unique_constraints("syntraflow_collections") if c.get("name")}
            if "uq_collection_hub_name" in existing_uqs:
                batch_op.drop_constraint("uq_collection_hub_name", type_="unique")
            if "uq_syntraflow_collections_hub_name" not in existing_uqs:
                batch_op.create_unique_constraint("uq_syntraflow_collections_hub_name", ["hub_id", "name"])
        batch_op.create_index(batch_op.f('ix_syntraflow_collections_name'), ['name'], unique=False)

    with op.batch_alter_table('syntraflow_documents', schema=None) as batch_op:
        batch_op.alter_column('collection_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_syntraflow_documents_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index('ix_syntraflow_documents_hub_col', ['hub_id', 'collection_id'], unique=False)

    with op.batch_alter_table('syntraflow_jobs', schema=None) as batch_op:
        batch_op.alter_column('collection_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_syntraflow_jobs_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index('ix_syntraflow_jobs_hub_status', ['hub_id', 'status'], unique=False)

    with op.batch_alter_table('user_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_user_invites_open_email'), postgresql_where="((status)::text = 'pending'::text)")

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('user_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_user_invites_open_email'), ['email'], unique=True, postgresql_where="((status)::text = 'pending'::text)")

    with op.batch_alter_table('syntraflow_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_syntraflow_jobs_hub_status')
        batch_op.drop_index(batch_op.f('ix_syntraflow_jobs_collection_id'))
        batch_op.alter_column('collection_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('syntraflow_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_syntraflow_documents_hub_col')
        batch_op.drop_index(batch_op.f('ix_syntraflow_documents_collection_id'))
        batch_op.alter_column('collection_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('syntraflow_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_syntraflow_collections_name'))
        batch_op.create_unique_constraint(batch_op.f('uq_collection_hub_name'), ['hub_id', 'name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('vector_dimension',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1024'))
        batch_op.alter_column('physical_name',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)

    with op.batch_alter_table('eval_test_suites', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('target_hub_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('target_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'agent'::character varying"))

    with op.batch_alter_table('eval_run_history', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('target_hub_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('target_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'agent'::character varying"))

    with op.batch_alter_table('eval_flow_traces', schema=None) as batch_op:
        if op.get_bind().dialect.name != "sqlite":
            try:
                batch_op.drop_constraint(None, type_='foreignkey')
                batch_op.drop_constraint(None, type_='foreignkey')
            except Exception:
                pass
            batch_op.create_foreign_key(batch_op.f('eval_flow_traces_run_id_fkey'), 'eval_run_history', ['run_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('workflow_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('agent_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_definitions_endpoint_slug'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_credentials_provider'))

    op.drop_table('provider_credentials')
    # ### end Alembic commands ###
