"""initial_baseline

Revision ID: d2e57c967822
Revises: 
Create Date: 2026-07-08 08:51:32.693424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e57c967822'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('vram_mb', sa.Integer(), nullable=True),
    sa.Column('vector_dim', sa.Integer(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('quantization', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syntraflow_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syntraflow_chunks_document_id'), 'syntraflow_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_syntraflow_chunks_id'), 'syntraflow_chunks', ['id'], unique=False)
    op.create_table('syntraflow_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('layout_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syntraflow_documents_id'), 'syntraflow_documents', ['id'], unique=False)
    op.create_table('syntraflow_video_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('visual_summary', sa.Text(), nullable=True),
    sa.Column('emotion_tags', sa.String(length=255), nullable=True),
    sa.Column('audio_events', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syntraflow_video_segments_id'), 'syntraflow_video_segments', ['id'], unique=False)
    op.create_table('syntraflow_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['syntraflow_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evalops_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evalops_reports_id'), 'evalops_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evalops_reports_id'), table_name='evalops_reports')
    op.drop_table('evalops_reports')
    op.drop_table('syntraflow_jobs')
    op.drop_index(op.f('ix_syntraflow_video_segments_id'), table_name='syntraflow_video_segments')
    op.drop_table('syntraflow_video_segments')
    op.drop_index(op.f('ix_syntraflow_documents_id'), table_name='syntraflow_documents')
    op.drop_table('syntraflow_documents')
    op.drop_index(op.f('ix_syntraflow_chunks_id'), table_name='syntraflow_chunks')
    op.drop_index(op.f('ix_syntraflow_chunks_document_id'), table_name='syntraflow_chunks')
    op.drop_table('syntraflow_chunks')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
